# Generated by Django 4.2.1 on 2023-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='media/store_logos/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='profile_picture',
            field=models.ImageField(upload_to='media/profile_pictures/'),
        ),
    ]
