# Generated by Django 4.2.1 on 2023-06-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_store_logo_alter_store_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/product_pictures/'),
        ),
    ]
